name: shaker
description: A g-code generator for shaker style panels
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  args: ^2.0.0
  logging: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
